var noname;if(!noname)noname={};noname.Charts={};noname.Charts.createPieChart=function(dataset){var plot=new noname.PiePlot(dataset);var chart=noname.Chart(plot);return chart};noname.Charts.createBarChart=function(dataset,xAxisLabel,yAxisLabel){var plot=new noname.CategoryPlot(dataset);plot.xAxis.label=xAxisLabel;plot.yAxis.label=yAxisLabel;plot.renderer=new noname.BarRenderer;var chart=noname.Chart(plot);return chart};
noname.Charts.createStackedBarChart=function(dataset,xAxisLabel,yAxisLabel){var plot=new noname.CategoryPlot(dataset);plot.xAxis.label=xAxisLabel;plot.yAxis.label=yAxisLabel;plot.renderer=new noname.StackedBarRenderer;var chart=noname.Chart(plot);return chart};
noname.Charts.createStackedAreaChart=function(dataset,xAxisLabel,yAxisLabel){var plot=new noname.CategoryPlot(dataset);plot.xAxis.label=xAxisLabel;plot.yAxis.label=yAxisLabel;plot.renderer=new noname.StackedAreaRenderer;var chart=noname.Chart(plot);return chart};noname.Charts.createLineChart=function(dataset,xAxisLabel,yAxisLabel){var plot=new noname.CategoryPlot(dataset);plot.xAxis.label=xAxisLabel;plot.yAxis.label=yAxisLabel;plot.renderer=new noname.LineRenderer;var chart=noname.Chart(plot);return chart};
noname.Charts.createScatterChart=function(dataset,xAxisLabel,yAxisLabel){var plot=new noname.XYPlot(dataset);plot.xAxis.label=xAxisLabel;plot.yAxis.label=yAxisLabel;plot.renderer=new noname.ScatterRenderer(plot);var chart=noname.Chart(plot);return chart};
noname.Charts.createXYLineChart=function(dataset,xAxisLabel,yAxisLabel){var plot=new noname.XYPlot(dataset);plot.xAxis.label=xAxisLabel;plot.yAxis.label=yAxisLabel;var renderer=new noname.XYLineRenderer;var chart=noname.Chart(plot);plot.setRenderer(renderer);return chart};
noname.Charts.createHistogram=function(dataset,xAxisLabel,yAxisLabel){var plot=new noname.XYPlot(dataset);plot.xAxis.label=xAxisLabel;plot.yAxis.label=yAxisLabel;var renderer=new noname.HistogramRenderer;var chart=noname.Chart(plot);plot.setRenderer(renderer);return chart};noname.Utils={};noname.Utils.makeArrayOf=function(value,length){var arr=[],i=length;while(i--)arr[i]=value;return arr};noname.Utils.findInArray=function(items,matcher){var length=items.length;for(var i=0;i<length;i++)if(matcher(items[i],i))return i;return-1};noname.Args={};noname.Args.require=function(arg,label){if(arg==null)throw new Error("Require argument '"+label+"' to be specified.");};noname.Args.requireNumber=function(arg,label){if(typeof arg!=="number")throw new Error("Require '"+label+"' to be a number.");};noname.Args.requireString=function(arg,label){if(typeof arg!=="string")throw new Error("Require '"+label+"' to be a string.");};noname.Chart=function(plot){var _elementId;var _width=400;var _height=240;var _margin={top:15,right:30,bottom:30,left:40};var _title;var _subtitle;var _plot=plot;var _listeners=[];function me(){}plot.addListener(me);plot.chart=me;me.elementId=function(str){if(!arguments.length)return _elementId;_elementId=str;return me};me.width=function(value){if(!arguments.length)return _width;_width=value;return me};me.height=function(value){if(!arguments.length)return _height;_height=value;return me};me.margin=
function(obj){if(!arguments.length)return _margin;_margin=obj;return me};me.plot=function(obj){if(!arguments.length)return _plot;_plot=obj;return me};me.plotChanged=function(plot){};me.build=function(id){me.elementId(id);var element=document.getElementById(id);var doc=element.ownerDocument;var win=document.defaultView||document.parentWindow;var container=d3.select("#"+id);var chart=this;var resize=function(){console.log("container resized "+element.clientWidth+", "+element.clientHeight);chart.width(element.clientWidth-
1).height(element.clientHeight-1);container.select("svg").remove();chart.build(id)};win.onresize=resize;var svg=container.append("svg").attr("width",_width).attr("height",_height).attr("overflow","hidden");var defs=svg.append("defs");var filter=defs.append("filter").attr("id","glow1");filter.append("feColorMatrix").attr("type","matrix").attr("values","0 0 0 0 0 0 0 0 0 0 0 0 0 0   0 0 0 0 0.7 0");filter.append("feGaussianBlur").attr("stdDeviation",2.5).attr("result","blur");var feMerge=filter.append("feMerge");
feMerge.append("feMergeNode").attr("in","blur");feMerge.append("feMergeNode").attr("in","SourceGraphic");var svgg=svg.append("g");svgg.append("rect").attr("x",0.5).attr("y",0.5).attr("width",_width-1).attr("height",_height-1).attr("style","fill:rgb(255,255,255);stroke-width:1;stroke:rgb(100,100,100)");_plot.build(this,svgg)};me.createLegend=function(plot,anchor,orientation,style){};me.draw=function(ctx,bounds){ctx.fillStyle="#DDDDDD";ctx.fillRect(bounds.x,bounds.y,bounds.width,bounds.height);var dataArea=
new noname.Rectangle(this.margin.left,this.margin.top,this.width-this.margin.left-this.margin.right,this.height-this.margin.top-this.margin.bottom);this.plot.draw(ctx,bounds,dataArea)};return me};noname.Colors={};noname.Colors.fancyLight=function(){return["#64E1D5","#E2D75E","#F0A4B5","#E7B16D","#C2D58D","#CCBDE4","#6DE4A8","#93D2E2","#AEE377","#A0D6B5"]};noname.Colors.fancyDark=function(){return["#3A6163","#8A553A","#4A6636","#814C57","#675A6F","#384027","#373B43","#59372C","#306950","#665D31"]};noname.Colors.iceCube=function(){return["#4CE4B7","#45756F","#C2D9BF","#58ADAF","#4EE9E1","#839C89","#3E8F74","#92E5C1","#99E5E0","#57BDAB"]};
noname.Colors.blueOcean=function(){return["#6E7094","#4F76DF","#292E39","#2E4476","#696A72","#4367A6","#5E62B7","#42759A","#2E3A59","#4278CA"]};noname.LinearAxis=function(label){if(!(this instanceof noname.LinearAxis))return new noname.LinearAxis;this.label=label;this.autoRange=true;this.autoRangeIncludeZero=false;this.lowerBound=0;this.upperBound=1;this.lowerMargin=0.05;this.upperMargin=0.05;this._listeners=[];this.nice=true;this.scaleD3=d3.scale.linear()};
noname.LinearAxis.prototype.updateDomain=function(min,max){var xrange=max-min;var lowAdj,highAdj;if(xrange>0){lowAdj=this.lowerMargin*xrange;highAdj=this.upperMargin*xrange}else{lowAdj=0.5;highAdj=0.5}this.lowerBound=min-lowAdj;this.upperBound=max+highAdj;this.scaleD3.domain([min-lowAdj,max+highAdj]);if(this.nice)this.scaleD3.nice()};noname.LinearAxis.prototype.valueToCoordinate=function(value,range){return range.lowerBound+(value-this.lowerBound)/(this.upperBound-this.lowerBound)*range.length()};
noname.LinearAxis.prototype.coordinateToValue=function(coordinate,range){return 0};noname.LinearAxis.prototype.addListener=function(listener){this._listeners.push(listener)};
noname.LinearAxis.prototype.draw=function(ctx,plot,bounds,dataArea){var edge=plot.axisEdge(this);if(edge===noname.RectangleEdge.LEFT){ctx.beginPath();ctx.moveTo(dataArea.x,dataArea.y);ctx.lineTo(dataArea.x,dataArea.y+dataArea.height);ctx.closePath();ctx.stroke();ctx.fillText(this.lowerBound,dataArea.x-15,dataArea.y+dataArea.height);ctx.fillText(this.upperBound,dataArea.x-15,dataArea.y)}else if(edge===noname.RectangleEdge.BOTTOM){ctx.beginPath();ctx.moveTo(dataArea.x,dataArea.y+dataArea.height);ctx.lineTo(dataArea.x+
dataArea.width,dataArea.y+dataArea.height);ctx.closePath();ctx.stroke();ctx.fillText(this.lowerBound,dataArea.x,dataArea.y+dataArea.height+15);ctx.fillText(this.upperBound,dataArea.x+dataArea.width,dataArea.y+dataArea.height+15)}};noname.OrdinalAxis=function(label){if(!(this instanceof noname.OrdinalAxis))return new noname.OrdinalAxis;this.label=label;this.lowerMargin=0.05;this.upperMargin=0.05;this.listeners=[];this.scaleD3=d3.scale.ordinal()};noname.OrdinalAxis.prototype.addListener=function(listener){this.listeners.push(listener)};noname.CategoryPlot=function(dataset){if(!(this instanceof noname.CategoryPlot))return new noname.CategoryPlot;this.xAxis=new noname.OrdinalAxis;this.yAxis=new noname.LinearAxis;this.dataset=dataset;this.dataset.addListener(this.datasetChanged);this.colors=d3.scale.category10();this.colors.domain(this.dataset.rowKeys);this.listeners=[];this.rotateTickLabels=false};noname.CategoryPlot.prototype.addListener=function(listener){this.listeners.push(listener)};
noname.CategoryPlot.prototype.datasetChanged=function(dataset){};
noname.CategoryPlot.prototype.build=function(chart,svg){var plotg=svg.append("g");var dx=chart.margin.left;var dy=chart.margin.top;plotg.attr("transform","translate("+dx.toString()+","+dy.toString()+")");var w=chart.width-chart.margin.left-chart.margin.right;this.xAxis.scaleD3.domain(this.dataset.data.columnKeys).rangeBands([0,w]);var bounds=this.renderer.bounds(this.dataset);var ymin=bounds[0];var ymax=bounds[1];var h=chart.height-chart.margin.top-chart.margin.bottom;var lowAdj;var highAdj;var yrange=
ymax-ymin;if(yrange>0){lowAdj=this.yAxis.lowerMargin*yrange;highAdj=this.yAxis.upperMargin*yrange}else{lowAdj=0.5;highAdj=0.5}this.yAxis.scaleD3.domain([ymin-lowAdj,ymax+highAdj]).nice().range([h,0]);var xAxisD3=d3.svg.axis().scale(this.xAxis.scaleD3).tickSize(5,3,1).tickSubdivide(10).tickPadding(5).orient("bottom");var yAxisD3=d3.svg.axis().scale(this.yAxis.scaleD3).tickSize(5,3,1).tickPadding(5).orient("left");var xAxisg=plotg.append("g").attr("class","x axis").attr("transform","translate(0,"+h+
")").call(xAxisD3);if(this.xAxis.rotateTickLabels)xAxisg.selectAll("text").attr("y",0).attr("x",9).attr("dy",".35em").attr("transform","rotate(90)").style("text-anchor","start");plotg.append("g").attr("class","y axis").call(yAxisD3);if(this.xAxis.label)plotg.append("text").attr("class","x label").attr("text-anchor","end").attr("x",w).attr("y",h-6).text(this.xAxis.label);if(this.yAxis.label)plotg.append("text").attr("class","y label").attr("text-anchor","end").attr("y",6).attr("dy",".75em").attr("transform",
"rotate(-90)").text(this.yAxis.label);this.renderer.build(chart,this,this.xAxis.scaleD3,this.yAxis.scaleD3,plotg)};noname.PiePlot=function(dataset){if(!(this instanceof noname.PiePlot))return new noname.PiePlot;this.dataset=dataset;this.dataset.addListener(this);this.colors=d3.scale.category10();this.colors.domain(this.dataset.keys);this.radius=100;this.labelAnchorRadius=1.1;this.innerRadius=0;this.toolTipHandler=null;this.listeners=[]};noname.PiePlot.prototype.addListener=function(listener){this.listeners.push(listener)};noname.PiePlot.prototype.datasetChanged=function(dataset){this.update(this.chart)};
noname.PiePlot.prototype.setDataset=function(dataset){this.dataset=dataset;this.dataset.addListener(this)};
noname.PiePlot.prototype.update=function(chart){var chartContainer=d3.select("#"+chart.elementId);var plotg=chartContainer.select(".plot");var arcInfo=this.layout(this.dataset.data.sections);var colors=this.colors;var toolTipHandler=this.toolTipHandler;var arcs=plotg.selectAll(".arc").data(arcInfo);arcs.enter().append("g").attr("class","arc").append("path").attr("d",this.arcGenerator).style("fill",function(d){return colors(d.data.key)}).style("stroke","#2E2E2E");arcs.select("path").attr("d",this.arcGenerator).style("fill",
function(d){return colors(d.data.key)}).on("mouseover",function(datum){if(toolTipHandler!==null)toolTipHandler.mouseover(d3.event.target,datum.data.key,d3.event.target.__data__)}).on("mouseout",function(d){if(toolTipHandler!==null);});arcs.exit().remove();var labels=plotg.selectAll(".labels").data(arcInfo);var labelFactor=this.labelAnchorRadius;var radius=this.radius;labels.enter().append("text").attr("class","labels").text(function(d){return d.data.key}).attr("dy",".35em");labels.transition().text(function(d){return d.data.key}).attr("transform",
function(d){var mid=(d.endAngle+d.startAngle)/2;var xx=radius*Math.sin(mid)*labelFactor;var yy=-radius*Math.cos(mid)*labelFactor;return"translate("+[xx,yy]+")"}).style("text-anchor",function(d){var mid=(d.endAngle+d.startAngle)/2;if(mid<Math.PI/6)return"middle";if(mid<Math.PI*5/6)return"start";if(mid<Math.PI*7/6)return"middle";if(mid<Math.PI*11/6)return"end";return"middle"});labels.exit().remove()};
noname.PiePlot.prototype.build=function(chart,svg){var plotg=svg.append("g").attr("class","plot");var w=chart.width-chart.margin.left-chart.margin.right;var h=chart.height-chart.margin.top-chart.margin.bottom;var dx=chart.margin.left+Math.round(w/2);var dy=chart.margin.top+Math.round(h/2);plotg.attr("transform","translate("+dx.toString()+","+dy.toString()+")");this.radius=Math.min(w,h)/2-10;this.layout=d3.layout.pie().sort(null).value(function(d){return d.value});this.arcGenerator=d3.svg.arc().outerRadius(this.radius).innerRadius(this.innerRadius);
this.update(chart)};var d3;noname.XYPlot=function(dataset){if(!(this instanceof noname.XYPlot))return new noname.XYPlot;this.xAxis=new noname.LinearAxis;this.yAxis=new noname.LinearAxis;this.updateBounds=false;this.renderer=new noname.ScatterRenderer;this.dataset=dataset;var listener=function(p){var plot=p;return function(dataset){plot.updateBounds=true;plot.update(plot.chart)}}(this);this.dataset.addListener(listener);this.listeners=[]};noname.XYPlot.prototype.addListener=function(obj){this.listeners.push(obj)};
noname.XYPlot.prototype.setDataset=function(dataset){this.dataset=dataset;this.dataset.addListener(this)};noname.XYPlot.prototype.rendererChanged=function(renderer){};noname.XYPlot.prototype.setRenderer=function(renderer){this.renderer=renderer};
noname.XYPlot.prototype.update=function(chart){var chartContainer=d3.select("#"+chart.elementId());var plotg=chartContainer.select(".plot");if(this.updateBounds){var bounds=this.dataset.bounds();var xmin=bounds[0];var xmax=bounds[1];var ymin=bounds[2];var ymax=bounds[3];this.xAxis.updateDomain(xmin,xmax);this.yAxis.updateDomain(ymin,ymax);this.zoomD3.x(this.xAxis.scaleD3).y(this.yAxis.scaleD3).scale(1).translate([0,0]);this.updateBounds=false}plotg.selectAll("g.x.axis").transition().call(this.xAxisD3);
plotg.selectAll("g.y.axis").transition().call(this.yAxisD3);this.renderer.update(chart,this,this.xAxis.scaleD3,this.yAxis.scaleD3,plotg)};
noname.XYPlot.prototype.build=function(chart,svg){var plotg=svg.append("g").attr("class","plot");var dx=chart.margin().left;var dy=chart.margin().top;plotg.attr("transform","translate("+dx.toString()+","+dy.toString()+")");var bounds=this.dataset.bounds();var xmin=bounds[0];var xmax=bounds[1];var ymin=bounds[2];var ymax=bounds[3];var w=chart.width()-chart.margin().left-chart.margin().right;var h=chart.height()-chart.margin().top-chart.margin().bottom;this.xAxis.updateDomain(xmin,xmax);this.xAxis.scaleD3.range([0,
w]);this.yAxis.updateDomain(ymin,ymax);this.yAxis.scaleD3.range([h,0]);this.xAxisD3=d3.svg.axis().scale(this.xAxis.scaleD3).tickSize(5,3,1).tickSubdivide(10).tickPadding(5).orient("bottom");this.yAxisD3=d3.svg.axis().scale(this.yAxis.scaleD3).tickSize(5,3,1).tickPadding(5).orient("left");plotg.append("g").attr("class","x axis").attr("transform","translate(0,"+h+")").call(this.xAxisD3);plotg.append("g").attr("class","y axis").call(this.yAxisD3);if(this.xAxis.label)plotg.append("text").attr("class",
"x label").attr("text-anchor","end").attr("x",w).attr("y",h-6).text(this.xAxis.label);if(this.yAxis.label)plotg.append("text").attr("class","y label").attr("text-anchor","end").attr("y",6).attr("dy",".75em").attr("transform","rotate(-90)").text(this.yAxis.label);svg.append("clipPath").attr("id","clip1").append("rect").attr("width",w).attr("height",h);var datag=plotg.append("g").attr("clip-path","url(#clip1)").attr("pointer-events","all");datag.append("rect").attr("x",dx).attr("y",dx).attr("width",
w).attr("height",h).attr("visibility","hidden");var xAxisD3=this.xAxisD3;var yAxisD3=this.yAxisD3;var plot=this;var zoom=function(){plot.update(plot.chart)};this.zoomD3=d3.behavior.zoom().x(this.xAxis.scaleD3).y(this.yAxis.scaleD3).on("zoom",zoom);datag.call(this.zoomD3);this.renderer.build(chart,this,this.xAxis.scaleD3,this.yAxis.scaleD3,datag)};noname.XYPlot.prototype.datasetChanged=function(dataset){this.updateBounds=true;this.update(this.chart)};
noname.XYPlot.prototype.autoCalcBounds=function(){this.updateBounds=true;this.update(this.chart)};noname.XYPlot.prototype.draw=function(ctx,bounds,dataArea){ctx.fillStyle="#FFFFFF";ctx.fillRect(dataArea.x,dataArea.y,dataArea.width,dataArea.height);this.drawAxes(ctx,bounds,dataArea);for(var s=0;s<this.dataset.seriesCount();s++)for(var i=0;i<this.dataset.itemCount(s);i++)this.renderer.drawItem(ctx,dataArea,this,this.dataset,s,i)};
noname.XYPlot.prototype.drawAxes=function(ctx,bounds,dataArea){ctx.fillStyle="#000000";this.xAxis.draw(ctx,this,bounds,dataArea);this.yAxis.draw(ctx,this,bounds,dataArea)};noname.XYPlot.prototype.axisEdge=function(axis){if(axis===this.xAxis)return noname.RectangleEdge.BOTTOM;else if(axis===this.yAxis)return noname.RectangleEdge.LEFT};noname.BarRenderer=function(){if(!(this instanceof noname.BarRenderer))return new noname.BarRenderer;this.colors=d3.scale.category10().range(noname.Colors.blueOcean());this.toolTipHandler=null;this.listeners=[]};noname.BarRenderer.prototype.bounds=function(dataset){return dataset.bounds()};noname.BarRenderer.prototype.build=function(chart,plot,xscale,yscale,datag){datag.append("g").attr("class","bar");this.update(chart,plot,xscale,yscale,datag)};
noname.BarRenderer.prototype.update=function(chart,plot,xscale,yscale,datag){var renderg=datag.select(".bar");var colorFunction=this.colors;var seriesg=renderg.selectAll(".series").data(plot.dataset.data.rows);var toolTipHandler=this.toolTipHandler;var seriesCount=plot.dataset.rowCount();var barWidth=xscale.rangeBand()/seriesCount;seriesg.enter().append("g").attr("class","series").attr("noname:seriesKey",function(d){return d.key});var itemg=seriesg.selectAll("rect").data(function(d){return d.values});
itemg.enter().append("rect").attr("transform",function(d,i){var rowKey=this.parentElement.__data__.key;var row=plot.dataset.rowIndex(rowKey);return"translate("+(i*xscale.rangeBand()+row*barWidth)+",0)"}).style("fill",function(d){var seriesKey=this.parentElement.__data__.key;return colorFunction(seriesKey)});itemg.attr("y",function(d){return Math.min(yscale(0),yscale(d))}).attr("height",function(d){return Math.abs(yscale(0)-yscale(d))}).attr("width",xscale.rangeBand()/seriesCount);itemg.exit().remove()};noname.HistogramRenderer=function(){if(!(this instanceof noname.HistogramRenderer))return new noname.HistogramRenderer;this.colors=d3.scale.category10();this.toolTipHandler=null;this.listeners=[]};noname.HistogramRenderer.prototype.build=function(chart,plot,xscale,yscale,datag){datag.append("g").attr("class","HistogramRenderer");this.update(chart,plot,xscale,yscale,datag)};
noname.HistogramRenderer.prototype.update=function(chart,plot,xscale,yscale,datag){var renderg=datag.select(".HistogramRenderer");var colorFunction=this.colors;var binsg=renderg.selectAll(".bins").data(plot.dataset.bins);binsg.enter().append("rect").attr("transform",function(bin,i){return"translate("+xscale(bin.xmin)+",0)"}).style("fill",function(bin){return colorFunction(bin)});binsg.attr("y",function(bin){var zero=yscale(0);var y=yscale(bin.count);return Math.min(yscale(0),yscale(bin.count))}).attr("height",
function(bin){var height=Math.abs(yscale(0)-yscale(bin.count));return height}).attr("width",function(bin){return xscale(bin.xmax)-xscale(bin.xmin)});binsg.exit().remove()};noname.LineRenderer=function(){if(!(this instanceof noname.LineRenderer))return new noname.LineRenderer;this.colors=d3.scale.category10();this.toolTipHandler=null;this.listeners=[]};noname.LineRenderer.prototype.bounds=function(dataset){return dataset.bounds()};noname.LineRenderer.prototype.build=function(chart,plot,xscale,yscale,datag){datag.append("g").attr("class","line");this.update(chart,plot,xscale,yscale,datag)};
noname.LineRenderer.prototype.update=function(chart,plot,xscale,yscale,datag){var renderg=datag.select(".line");var colorFunction=this.colors;var seriesg=renderg.selectAll(".series").data(plot.dataset.data.rows);var toolTipHandler=this.toolTipHandler;var lineGenerator=d3.svg.line().x(function(d,i){var colkey=plot.dataset.data.columnKeys[i];var x0=xscale(colkey);var ww=xscale.rangeBand();return x0+ww/2}).y(function(d){var yy=yscale(d);return yy}).interpolate("linear");seriesg.enter().append("g").attr("class",
"series").attr("noname:seriesKey",function(d){return d.key}).append("path").attr("d",function(d){return lineGenerator(d.values)}).style("stroke",function(d){return colorFunction(d.key)}).style("fill","none");seriesg.select("path").attr("d",function(d){return lineGenerator(d.values)})};noname.ScatterRenderer=function(plot){if(!(this instanceof noname.ScatterRenderer))return new noname.ScatterRenderer;this.plot=plot;this.colors=d3.scale.category10();this.radius=3;this.toolTipHandler=null;this.listeners=[]};noname.ScatterRenderer.prototype.itemFillColor=function(seriesKey,itemKey){var c=this.plot.dataset.getProperty(seriesKey,itemKey,"color");if(c)return c;return this.colors(seriesKey)};
noname.ScatterRenderer.prototype.itemStrokeColor=function(seriesKey,itemKey){if(this.plot.dataset.isSelected("select",seriesKey,itemKey))return"red";return"none"};
noname.ScatterRenderer.prototype.update=function(chart,plot,xscale,yscale,datag){var renderg=datag.select(".scatter");var me=this;var seriesg=renderg.selectAll(".series").data(plot.dataset.data.series);var toolTipHandler=this.toolTipHandler;seriesg.enter().append("g").attr("class","series").attr("noname:seriesKey",function(d){return d.seriesKey}).on("mouseover",function(datum){if(toolTipHandler);}).on("mouseout",function(d){if(toolTipHandler);});seriesg.exit().remove();var itemg=seriesg.selectAll("circle").data(function(d){return d.items},
function(d,i){return d.key});itemg.enter().append("circle").attr("r",0).attr("cx",function(d){return xscale(d.x)}).attr("cy",function(d){return yscale(d.y)}).style("fill",function(d){var seriesKey=this.parentNode.__data__.seriesKey;return me.itemFillColor(seriesKey,d.key)}).style("stroke",function(d){var seriesKey=this.parentNode.__data__.seriesKey;return me.itemStrokeColor(seriesKey,d.key)}).style("filter",function(d){var seriesKey=this.parentNode.__data__.seriesKey;if(me.plot.dataset.isSelected("hilite",
seriesKey,d.key))return"url(#glow1)";return"none"});itemg.transition().duration(300).attr("cx",function(d){return xscale(d.x)}).attr("cy",function(d){return yscale(d.y)}).attr("r",this.radius);itemg.exit().remove()};noname.ScatterRenderer.prototype.build=function(chart,plot,xscale,yscale,datag){datag.append("g").attr("class","scatter");this.update(chart,plot,xscale,yscale,datag)};
noname.ScatterRenderer.prototype.drawItem=function(ctx,dataArea,plot,dataset,seriesIndex,itemIndex){var x=dataset.x(seriesIndex,itemIndex);var y=dataset.y(seriesIndex,itemIndex);var xRange=new noname.Range(dataArea.x,dataArea.x+dataArea.width);var yRange=new noname.Range(dataArea.y,dataArea.y+dataArea.height);var xx=plot.xAxis.valueToCoordinate(x,xRange);var yy=plot.yAxis.valueToCoordinate(y,yRange);ctx.fillStyle=this.colors(seriesIndex);ctx.fillRect(xx-2,yy-2,4,4)};noname.StackedAreaRenderer=function(){if(!(this instanceof noname.StackedAreaRenderer))return new noname.StackedAreaRenderer;this.colors=d3.scale.category10().range(noname.Colors.fancyLight());this.toolTipHandler=null;this.listeners=[];this.offset="zero"};noname.StackedAreaRenderer.prototype.bounds=function(dataset){var bounds=dataset.bounds();return[bounds[0]-6,bounds[1]+6]};
noname.StackedAreaRenderer.prototype.layers=function(dataset){var layers=[];var rowKeys=dataset.rowKeys();var rowObjs=[];rowKeys.forEach(function(rowKey){rowObjs[rowKey]={rowKey:rowKey,values:[]};layers.push(rowObjs[rowKey])});var colKeys=dataset.columnKeys();colKeys.forEach(function(colKey){rowKeys.forEach(function(rowKey){rowObjs[rowKey].values.push({colKey:colKey,value:dataset.valueByKey(rowKey,colKey)})})});return layers};
noname.StackedAreaRenderer.prototype.build=function(chart,plot,xscale,yscale,datag){datag.append("g").attr("class","stackedarea");this.update(chart,plot,xscale,yscale,datag)};
noname.StackedAreaRenderer.prototype.update=function(chart,plot,xscale,yscale,datag){var renderg=datag.select(".stackedarea");var colorFunction=this.colors;var layers=this.layers(plot.dataset);var stack=d3.layout.stack().offset(this.offset).values(function(row){return row.values}).x(function(d){return xscale(d.colKey)+xscale.rangeBand()/2}).y(function(d){return d.value});var seriesg=renderg.selectAll(".series").data(stack(layers)).enter().append("g").attr("class","series");yscale.domain([0,d3.max(layers,
function(c){return d3.max(c.values,function(d){return d.y0+d.y})})]);var toolTipHandler=this.toolTipHandler;var area=d3.svg.area().interpolate("cardinal").x(function(d){return xscale(d.colKey)+xscale.rangeBand()/2}).y0(function(d){return yscale(d.y0)}).y1(function(d){return yscale(d.y0+d.y)});seriesg.append("path").attr("class","streamPath").attr("d",function(d){return area(d.values)}).style("fill",function(d){return colorFunction(d.rowKey)})};noname.StackedBarRenderer=function(){if(!(this instanceof noname.StackedBarRenderer))return new noname.StackedBarRenderer;this.colors=d3.scale.category10().range(noname.Colors.iceCube());this.toolTipHandler=null;this.listeners=[]};
noname.StackedBarRenderer.prototype.bounds=function(dataset){var stackBaseValues=noname.DatasetUtils.extractStackBaseValues(dataset);var rowKeys=dataset.rowKeys();var columnKeys=dataset.columnKeys();var min;var max;rowKeys.forEach(function(rowKey){columnKeys.forEach(function(columnKey){var base=stackBaseValues.valueByKey(rowKey,columnKey);var y=dataset.valueByKey(rowKey,columnKey);if(min)min=Math.min(min,base+y);else min=base+y;if(max)max=Math.max(max,base+y);else max=base+y})});return[min,max]};
noname.StackedBarRenderer.prototype.build=function(chart,plot,xscale,yscale,datag){datag.append("g").attr("class","stackedbar");this.update(chart,plot,xscale,yscale,datag)};
noname.StackedBarRenderer.prototype.update=function(chart,plot,xscale,yscale,datag){var renderg=datag.select(".stackedbar");var colorFunction=this.colors;var stackBaseValues=noname.DatasetUtils.extractStackBaseValues(plot.dataset);var seriesg=renderg.selectAll(".series").data(plot.dataset.data.rows);var toolTipHandler=this.toolTipHandler;var barWidth=xscale.rangeBand();seriesg.enter().append("g").attr("class","series").attr("noname:seriesKey",function(d){return d[0]});var itemg=seriesg.selectAll("rect").data(function(d){return d.values});
itemg.enter().append("rect").attr("transform",function(d,i){return"translate("+i*xscale.rangeBand()+",0)"}).style("fill",function(d){var seriesKey=this.parentElement.__data__.key;return colorFunction(seriesKey)});itemg.attr("y",function(d,i){var rowKey=this.parentElement.__data__.key;var row=plot.dataset.rowIndex(rowKey);var base=stackBaseValues.valueByIndex(row,i);return Math.min(yscale(base),yscale(base+d))}).attr("height",function(d){return Math.abs(yscale(0)-yscale(d))}).attr("width",xscale.rangeBand());
itemg.exit().remove()};noname.XYLineRenderer=function(){if(!(this instanceof noname.XYLineRenderer))return new noname.XYLineRenderer;this.colors=d3.scale.category10();this.toolTipHandler=null;this.listeners=[]};noname.XYLineRenderer.prototype.build=function(chart,plot,xscale,yscale,datag){datag.append("g").attr("class","line");this.update(chart,plot,xscale,yscale,datag)};
noname.XYLineRenderer.prototype.update=function(chart,plot,xscale,yscale,datag){var renderg=datag.select(".line");var colorFunction=this.colors;var seriesg=renderg.selectAll(".series").data(plot.dataset.data.series);var toolTipHandler=this.toolTipHandler;var lineGenerator=d3.svg.line().x(function(d){return xscale(d.x)}).y(function(d){return yscale(d.y)}).interpolate("linear");seriesg.enter().append("g").attr("class","series").attr("noname:seriesKey",function(d){return d.seriesKey}).append("path").attr("d",
function(d){return lineGenerator(d.items)}).style("stroke",function(d){return colorFunction(d.seriesKey)}).style("fill","none");seriesg.select("path").attr("d",function(d){return lineGenerator(d.items)})};noname.Bin=function(xmin,xmax,incmin,incmax){this.xmin=xmin;this.xmax=xmax;this.incMin=incmin!==false;this.incMax=incmax!==false;this.count=0};noname.Bin.prototype.includes=function(value){if(value<this.xmin)return false;if(value===this.xmin)return this.incMin;if(value>this.xmax)return false;if(value===this.xmax)return this.incMax;return true};
noname.Bin.prototype.overlaps=function(bin){if(this.xmax<bin.xmin)return false;if(this.xmin>bin.xmax)return false;if(this.xmax===bin.xmin)if(!(this.incMax&&bin.incMin))return false;if(this.xmin===bin.xmax)if(!(this.incMin&&bin.incMax))return false;return true};noname.DatasetUtils={};
noname.DatasetUtils.extractStackBaseValues=function(dataset,baseline){baseline=typeof baseline!=="undefined"?baseline:0;var result=new noname.KeyedValues2DDataset;var columnCount=dataset.columnCount();var rowCount=dataset.rowCount();for(var c=0;c<columnCount;c++){var columnKey=dataset.columnKey(c);var posBase=baseline;var negBase=baseline;for(var r=0;r<rowCount;r++){var y=dataset.valueByIndex(r,c);var rowKey=dataset.rowKey(r);if(r>0)if(y>=0)result.add(rowKey,columnKey,posBase);else result.add(rowKey,
columnKey,negBase);else result.add(rowKey,columnKey,baseline);if(y>0)posBase=posBase+y;if(y<0)negBase=negBase+y}}return result};
noname.DatasetUtils.extractXYDatasetFromColumns=function(dataset,xcol,ycol){var result=new noname.XYDataset;for(var s=0;s<dataset.seriesCount();s++){var seriesKey=dataset.seriesKey(s);for(var r=0;r<dataset.rowCount();r++){var rowKey=dataset.rowKey(r);var x=dataset.valueByKey(seriesKey,rowKey,xcol);var xPropKeys=dataset.propertyKeys(seriesKey,rowKey,xcol);var y=dataset.valueByKey(seriesKey,rowKey,ycol);var yPropKeys=dataset.propertyKeys(seriesKey,rowKey,ycol);result.add(seriesKey,x,y);var itemKey=
result.getItemKey(s,result.itemCount(s)-1);xPropKeys.forEach(function(key){var p=dataset.getProperty(seriesKey,rowKey,xcol,key);result.setProperty(seriesKey,itemKey,key,p)});yPropKeys.forEach(function(key){var p=dataset.getProperty(seriesKey,rowKey,ycol,key);result.setProperty(seriesKey,itemKey,key,p)})}}return result};
noname.DatasetUtils.extractXYDatasetFromRows=function(dataset,xrow,yrow){var result=new noname.XYDataset;for(var s=0;s<dataset.seriesCount();s++){var seriesKey=dataset.seriesKey(s);for(var c=0;c<dataset.columnCount();c++){var colKey=dataset.columnKey(c);var x=dataset.valueByKey(seriesKey,xrow,colKey);var xPropKeys=dataset.propertyKeys(seriesKey,xrow,colKey);var y=dataset.valueByKey(seriesKey,yrow,colKey);var yPropKeys=dataset.propertyKeys(seriesKey,yrow,colKey);var itemKey=result.getItemKey(s,result.itemCount(s)-
1);xPropKeys.forEach(function(key){var p=dataset.getProperty(seriesKey,xrow,colKey,key);result.setProperty(seriesKey,itemKey,key,p)});yPropKeys.forEach(function(key){var p=dataset.getProperty(seriesKey,yrow,colKey,key);result.setProperty(seriesKey,itemKey,key,p)});result.add(seriesKey,x,y)}}return result};noname.Map=function(){this.data=[]};noname.Map.prototype.keys=function(){return this.data.map(function(d){return d.key})};noname.Map.prototype._indexOf=function(key){for(var i=0;i<this.data.length;i++)if(this.data[i].key===key)return i;return-1};noname.Map.prototype.put=function(key,value){var i=this._indexOf(key);if(i<0)this.data.push({"key":key,"value":value});else this.data[i].value=value};noname.Map.prototype.get=function(key){var i=this._indexOf(key);if(i>=0)return this.data[i].value;else return undefined};
noname.Map.prototype.remove=function(key){var i=this._indexOf(key);if(i>=0)return this.data.splice(i,1)};noname.Range=function(lowerBound,upperBound){this.lowerBound=lowerBound;this.upperBound=upperBound};noname.Range.prototype.length=function(){return this.upperBound-this.lowerBound};noname.HistogramDataset=function(){this.bins=[];this.selections=[];this._listeners=[]};noname.HistogramDataset.prototype.binCount=function(){return this.bins.length};noname.HistogramDataset.prototype.isEmpty=function(){var result=true;this.bins.forEach(function(bin){if(bin.count>0)result=false});return result};noname.HistogramDataset.prototype.addListener=function(listenerObj){this._listeners.push(listenerObj);return this};
noname.HistogramDataset.prototype.removeListener=function(listenerObj){var i=this._listeners.indexOf(listenerObj);if(i>=0)this._listeners.splice(i,1);return this};noname.HistogramDataset.prototype.notifyListeners=function(){for(var i=0;i<this._listeners.length;i++)this._listeners[i].datasetChanged(this);return this};
noname.HistogramDataset.prototype.addBin=function(xmin,xmax,incmin,incmax){var incmin_=incmin!==false;var incmax_=incmax!==false;var bin=new noname.Bin(xmin,xmax,incmin_,incmax_);this.bins.push(bin);return this};noname.HistogramDataset.prototype.isOverlapping=function(bin){for(var i=0;i<this.bins.length;i++)if(this.bins[i].overlaps(bin))return true;return false};noname.HistogramDataset.prototype.x=function(binIndex){var bin=this.bins[binIndex];return(bin.xmin+bin.xmax)/2};
noname.HistogramDataset.prototype.xstart=function(binIndex){return this.bins[binIndex].xmin};noname.HistogramDataset.prototype.xend=function(binIndex){return this.bins[binIndex].xmax};noname.HistogramDataset.prototype.y=function(binIndex){return this.bins[binIndex].summaryValue};noname.HistogramDataset.prototype.reset=function(){this.bins.forEach(function(bin){bin.count=0});return this};
noname.HistogramDataset.prototype._binIndex=function(value){for(var i=0;i<this.bins.length;i++)if(this.bins[i].includes(value))return i;return-1};noname.HistogramDataset.prototype.bounds=function(){var xmin=Number.POSITIVE_INFINITY;var xmax=Number.NEGATIVE_INFINITY;var ymin=0;var ymax=0;for(var i=0;i<this.binCount();i++){var bin=this.bins[i];xmin=Math.min(xmin,bin.xmin);xmax=Math.max(xmax,bin.xmax);ymin=Math.min(ymin,bin.y);ymax=Math.max(ymax,bin.y)}return[xmin,xmax,ymin,ymax]};
noname.HistogramDataset.prototype.add=function(value,notify){var notify=notify!==false;var binIndex=this._binIndex(value);if(binIndex>=0)this.bins[binIndex].count++;else throw new Error("No bin for the value "+value);return this};noname.HistogramDataset.prototype.addAll=function(values,notify){var notify=notify!==false;values.forEach(function(v){this.add(v,false)});return this};noname.KeyedValuesDataset=function(){if(!(this instanceof noname.KeyedValuesDataset))return new noname.KeyedValuesDataset;this.data={"sections":[]};this.properties=[];this.selections=[];this._listeners=[]};noname.KeyedValuesDataset.prototype.itemCount=function(){return this.data.sections.length};noname.KeyedValuesDataset.prototype.isEmpty=function(){return this.data.sections.length===0};noname.KeyedValuesDataset.prototype.key=function(index){return this.data.sections[index].key};
noname.KeyedValuesDataset.prototype.keys=function(){return this.data.sections.map(function(d){return d.key})};noname.KeyedValuesDataset.prototype.indexOf=function(sectionKey){var arrayLength=this.data.sections.length;for(var i=0;i<arrayLength;i++)if(this.data.sections[i].key===sectionKey)return i;return-1};noname.KeyedValuesDataset.prototype.valueByIndex=function(index){return this.data.sections[index].value};
noname.KeyedValuesDataset.prototype.valueByKey=function(sectionKey){var sectionIndex=this.indexOf(sectionKey);if(sectionIndex<0)return null;return this.valueByIndex(sectionIndex)};noname.KeyedValuesDataset.prototype.addListener=function(listener){this._listeners.push(listener);return this};noname.KeyedValuesDataset.prototype.removeListener=function(listener){var i=this._listeners.indexOf(listener);if(i>=0)this._listeners.splice(i,1);return this};
noname.KeyedValuesDataset.prototype.notifyListeners=function(){for(var i=0;i<this._listeners.length;i++)this._listeners[i].datasetChanged(this);return this};noname.KeyedValuesDataset.prototype.add=function(sectionKey,value,notify){var notify=notify!==false;var i=this.indexOf(sectionKey);if(i<0){this.data.sections.push({"key":sectionKey,"value":value});this.properties.push(new noname.Map)}else this.data.sections[i].value=value;if(notify)this.notifyListeners();return this};
noname.KeyedValuesDataset.prototype.remove=function(sectionKey,notify){var notify=notify!==false;if(!sectionKey)throw new Error("The 'sectionKey' must be defined.");var i=this.indexOf(sectionKey);if(i<0)throw new Error("The sectionKey '"+sectionKey.toString()+"' is not recognised.");this.data.sections.splice(i,1);this.properties.splice(i,1);if(notify)this.notifyListeners();return this};
noname.KeyedValuesDataset.prototype.parse=function(jsonStr,notify){var notify=notify!==false;this.data.sections=JSON.parse(jsonStr);if(notify)this.notifyListeners();return this};noname.KeyedValuesDataset.prototype.load=function(data,notify){var notify=notify!==false;this.data.sections=data;if(notify)this.notifyListeners();return this};noname.KeyedValuesDataset.prototype.removeByIndex=function(itemIndex){this.data.sections.splice(itemIndex,1);this.properties.splice(itemIndex,1);return this};
noname.KeyedValuesDataset.prototype.totalForDataset=function(dataset){var total=0;var itemCount=dataset.itemCount();for(var i=0;i<itemCount;i++){var v=dataset.valueByIndex(i);if(v)total=total+v}return total};noname.KeyedValuesDataset.prototype.minForDataset=function(dataset){var min=Number.NaN;var itemCount=dataset.itemCount();for(var i=0;i<itemCount;i++){var v=dataset.valueByIndex(i);if(v)if(min)min=Math.min(min,v);else min=v}return min};
noname.KeyedValuesDataset.prototype.maxForDataset=function(dataset){var max=Number.NaN;var itemCount=dataset.itemCount();for(var i=0;i<itemCount;i++){var v=dataset.valueByIndex(i);if(v)if(max)max=Math.max(max,v);else max=v}return max};noname.KeyedValuesDataset.prototype.total=function(){return this.totalForDataset(this)};noname.KeyedValuesDataset.prototype.min=function(){return this.minForDataset(this)};noname.KeyedValuesDataset.prototype.max=function(){return this.maxForDataset(this)};
noname.KeyedValuesDataset.prototype.propertyKeys=function(sectionKey){var i=this.indexOf(sectionKey);var map=this.properties[i];if(map)return map.keys();else return[]};noname.KeyedValuesDataset.prototype.getProperty=function(sectionKey,propertyKey){var i=this.indexOf(sectionKey);return this.properties[i].get(propertyKey)};
noname.KeyedValuesDataset.prototype.setProperty=function(sectionKey,propertyKey,value){var i=this.indexOf(sectionKey);if(i<0)throw new Error("Did not recognise 'sectionKey' "+sectionKey);var map=this.properties[i];map.put(propertyKey,value)};noname.KeyedValuesDataset.prototype.clearProperties=function(sectionKey){var i=this.indexOf(sectionKey);this.properties[i]=new noname.Map};
noname.KeyedValuesDataset.prototype.select=function(selectionId,key){var selection;var selectionIndex=this._indexOfSelection(selectionId);if(selectionIndex<0){selection={"id":selectionId,"items":[]};this.selections.push(selection)}else selection=this.selections[selectionIndex];var i=selection.items.indexOf(key);if(i<0)selection.items.push(key);return this};
noname.KeyedValuesDataset.prototype.unselect=function(selectionId,key){var selectionIndex=this._indexOfSelection(selectionId);if(selectionIndex>=0){var selection=this.selections[selectionIndex];var i=selection.items.indexOf(key);if(i>=0)selection.items.splice(i,1)}return this};
noname.KeyedValuesDataset.prototype.isSelected=function(selectionId,key){var selection;var selectionIndex=this._indexOfSelection(selectionId);if(selectionIndex<0)return false;else{selection=this.selections[selectionIndex];return selection.items.indexOf(key)>=0}};noname.KeyedValuesDataset.prototype.clearSelection=function(selectionId,notify){var selectionIndex=this._indexOfSelection(selectionId);if(selectionIndex>=0)this.selections.splice(selectionIndex,1);return this};
noname.KeyedValuesDataset.prototype._indexOfSelection=function(selectionId){return noname.Utils.findInArray(this.selections,function(selection){return selection.id===selectionId})};noname.KeyedValues2DDataset=function(){if(!(this instanceof noname.KeyedValues2DDataset))return new noname.KeyedValues2DDataset;this.data={"columnKeys":[],"rows":[]};this.properties=[];this.selections=[];this._listeners=[]};noname.KeyedValues2DDataset.prototype.rowCount=function(){return this.data.rows.length};noname.KeyedValues2DDataset.prototype.columnCount=function(){return this.data.columnKeys.length};
noname.KeyedValues2DDataset.prototype.isEmpty=function(){if(!this.data.hasOwnProperty("columnKeys"))return true;return this.data.columnKeys.length===0&&this.data.rows.length===0};noname.KeyedValues2DDataset.prototype.addListener=function(listener){this._listeners.push(listener);return this};noname.KeyedValues2DDataset.prototype.removeListener=function(listener){var i=this._listeners.indexOf(listener);if(i>=0)this._listeners.splice(i,1);return this};
noname.KeyedValues2DDataset.prototype.notifyListeners=function(){for(var i=0;i<this._listeners.length;i++)this._listeners[i].datasetChanged(this);return this};
noname.KeyedValues2DDataset.prototype.add=function(rowKey,columnKey,value,notify){if(this.isEmpty()){this.data.columnKeys.push(columnKey);this.data.rows.push({"key":rowKey,"values":[value]});this.properties.push({"key":rowKey,"maps":[null]});return this}var columnIndex=this.columnIndex(columnKey);if(columnIndex<0){this.data.columnKeys.push(columnKey);var rowCount=this.data.rows.length;for(var r=0;r<rowCount;r++){this.data.rows[r].values.push(null);this.properties[r].maps.push(null)}columnIndex=this.columnCount()-
1}var rowIndex=this.rowIndex(rowKey);if(rowIndex<0){var rowData=new Array(this.columnCount());rowData[columnIndex]=value;this.data.rows.push({"key":rowKey,"values":rowData});var rowProperties=new Array(this.columnCount());this.properties.push({"key":rowKey,"maps":rowProperties})}else this.data.rows[rowIndex].values[columnIndex]=value;return this};
noname.KeyedValues2DDataset.prototype.parse=function(jsonStr,notify){var notify=notify!==false;this.load(JSON.parse(jsonStr));if(notify)this.notifyListeners();return this};noname.KeyedValues2DDataset.prototype.load=function(data,notify){var notify=notify!==false;this.data=data;if(!this.data.hasOwnProperty("rows"))this.data.rows=[];if(!this.data.hasOwnProperty("columnKeys"))this.data.columnKeys=[];if(notify)this.notifyListeners();return this};
noname.KeyedValues2DDataset.prototype.valueByIndex=function(rowIndex,columnIndex){return this.data.rows[rowIndex].values[columnIndex]};noname.KeyedValues2DDataset.prototype.rowKey=function(rowIndex){return this.data.rows[rowIndex].key};noname.KeyedValues2DDataset.prototype.rowIndex=function(rowKey){var rowCount=this.data.rows.length;for(var r=0;r<rowCount;r++)if(this.data.rows[r].key===rowKey)return r;return-1};noname.KeyedValues2DDataset.prototype.rowKeys=function(){return this.data.rows.map(function(d){return d.key})};
noname.KeyedValues2DDataset.prototype.columnKey=function(columnIndex){return this.data.columnKeys[columnIndex]};noname.KeyedValues2DDataset.prototype.columnIndex=function(columnKey){var columnCount=this.data.columnKeys.length;for(var c=0;c<columnCount;c++)if(this.data.columnKeys[c]===columnKey)return c;return-1};noname.KeyedValues2DDataset.prototype.columnKeys=function(){return this.data.columnKeys.map(function(d){return d})};
noname.KeyedValues2DDataset.prototype.valueByKey=function(rowKey,columnKey){var rowIndex=this.rowIndex(rowKey);var columnIndex=this.columnIndex(columnKey);return this.valueByIndex(rowIndex,columnIndex)};noname.KeyedValues2DDataset.prototype.minForDataset=function(dataset){var min=Number.NaN;var rowCount=dataset.rowCount();var columnCount=dataset.columnCount();for(var r=0;r<rowCount;r++)for(var c=0;c<columnCount;c++){var v=dataset.valueByIndex(r,c);if(v)if(min)min=Math.min(min,v);else min=v}return min};
noname.KeyedValues2DDataset.prototype.maxForDataset=function(dataset){var max=Number.NaN;var rowCount=dataset.rowCount();var columnCount=dataset.columnCount();for(var r=0;r<rowCount;r++)for(var c=0;c<columnCount;c++){var v=dataset.valueByIndex(r,c);if(v)if(max)max=Math.max(max,v);else max=v}return max};noname.KeyedValues2DDataset.prototype.min=function(){return this.minForDataset(this)};noname.KeyedValues2DDataset.prototype.max=function(){return this.maxForDataset(this)};
noname.KeyedValues2DDataset.prototype.yValues=function(rowIndex){return this.data.rows[rowIndex].values.map(function(d){return d})};noname.KeyedValues2DDataset.prototype.bounds=function(){var ymin=Number.POSITIVE_INFINITY;var ymax=Number.NEGATIVE_INFINITY;var rowCount=this.rowCount();var columnCount=this.columnCount();for(var r=0;r<rowCount;r++)for(var c=0;c<columnCount;c++){var v=this.valueByIndex(r,c);if(v){ymin=Math.min(ymin,v);ymax=Math.max(ymax,v)}}return[ymin,ymax]};
noname.KeyedValues2DDataset.prototype.getProperty=function(rowKey,columnKey,propertyKey){var rowIndex=this.rowIndex(rowKey);var columnIndex=this.columnIndex(columnKey);var map=this.properties[rowIndex][columnIndex];if(map)return map.get(propertyKey)};
noname.KeyedValues2DDataset.prototype.setProperty=function(rowKey,columnKey,propertyKey,value){var rowIndex=this.rowIndex(rowKey);var columnIndex=this.columnIndex(columnKey);var map=this.properties[rowIndex][columnIndex];if(!map){map=new noname.Map;this.properties[rowIndex][columnIndex]=map}map.put(propertyKey,value)};
noname.KeyedValues2DDataset.prototype.clearProperties=function(rowKey,columnKey){var rowIndex=this.rowIndex(rowKey);var columnIndex=this.columnIndex(columnKey);this.properties[rowIndex][columnIndex]=null};
noname.KeyedValues2DDataset.prototype.select=function(selectionId,rowKey,columnKey){var selection;var selectionIndex=this._indexOfSelection(selectionId);if(selectionIndex<0){selection={"id":selectionId,"items":[]};this.selections.push(selection)}else selection=this.selections[selectionIndex];var i=noname.Utils.findInArray(selection.items,function(item){return item.rowKey===rowKey&&item.columnKey===columnKey});if(i<0)selection.items.push({"rowKey":rowKey,"columnKey":columnKey});return this};
noname.KeyedValues2DDataset.prototype.unselect=function(selectionId,rowKey,columnKey){var selectionIndex=this._indexOfSelection(selectionId);if(selectionIndex>=0){var selection=this.selections[selectionIndex];var i=noname.Utils.findInArray(selection.items,function(obj,i){return obj.rowKey===rowKey&&obj.columnKey===columnKey});if(i>=0)selection.items.splice(i,1)}return this};
noname.KeyedValues2DDataset.prototype.isSelected=function(selectionId,rowKey,columnKey){var selection;var selectionIndex=this._indexOfSelection(selectionId);if(selectionIndex<0)return false;else selection=this.selections[selectionIndex];return noname.Utils.findInArray(selection.items,function(obj){return obj.rowKey===rowKey&&obj.columnKey===columnKey})>=0};
noname.KeyedValues2DDataset.prototype.clearSelection=function(selectionId){var selectionIndex=this._indexOfSelection(selectionId);if(selectionIndex>=0)this.selections.splice(selectionIndex,1);return this};noname.KeyedValues2DDataset.prototype._indexOfSelection=function(selectionId){return noname.Utils.findInArray(this.selections,function(item){return item.id===selectionId})};noname.KeyedValues3DDataset=function(){if(!(this instanceof noname.KeyedValues3DDataset))return new noname.KeyedValues3DDataset;this.data={"columnKeys":[],"rowKeys":[],"series":[]};this.properties=[];this._listeners=[]};noname.KeyedValues3DDataset.prototype.isEmpty=function(){return this.data.columnKeys.length===0&&this.data.rowKeys.length===0};noname.KeyedValues3DDataset.prototype.seriesCount=function(){return this.data.series.length};noname.KeyedValues3DDataset.prototype.rowCount=function(){return this.data.rowKeys.length};
noname.KeyedValues3DDataset.prototype.columnCount=function(){return this.data.columnKeys.length};noname.KeyedValues3DDataset.prototype._fetchRow=function(seriesIndex,rowKey){var rows=this.data.series[seriesIndex].rows;for(var r=0;r<rows.length;r++)if(rows[r].rowKey===rowKey)return rows[r];return null};noname.KeyedValues3DDataset.prototype.valueByIndex=function(seriesIndex,rowIndex,columnIndex){var rowKey=this.rowKey(rowIndex);var row=this._fetchRow(seriesIndex,rowKey);if(row===null)return null;else return row.values[columnIndex]};
noname.KeyedValues3DDataset.prototype.seriesIndex=function(seriesKey){var seriesCount=this.seriesCount();for(var s=0;s<seriesCount;s++)if(this.data.series[s].seriesKey===seriesKey)return s;return-1};noname.KeyedValues3DDataset.prototype.seriesKey=function(seriesIndex){return this.data.series[seriesIndex].seriesKey};noname.KeyedValues3DDataset.prototype.rowKey=function(rowIndex){return this.data.rowKeys[rowIndex]};
noname.KeyedValues3DDataset.prototype.rowIndex=function(rowKey){var rowCount=this.data.rowKeys.length;for(var r=0;r<rowCount;r++)if(this.data.rowKeys[r]===rowKey)return r;return-1};noname.KeyedValues3DDataset.prototype.rowKeys=function(){return this.data.rowKeys.map(function(d){return d})};noname.KeyedValues3DDataset.prototype.columnKey=function(columnIndex){return this.data.columnKeys[columnIndex]};
noname.KeyedValues3DDataset.prototype.columnIndex=function(columnKey){var columnCount=this.data.columnKeys.length;for(var c=0;c<columnCount;c++)if(this.data.columnKeys[c]===columnKey)return c;return-1};noname.KeyedValues3DDataset.prototype.columnKeys=function(){return this.data.columnKeys.map(function(d){return d})};
noname.KeyedValues3DDataset.prototype.valueByKey=function(seriesKey,rowKey,columnKey){var seriesIndex=this.seriesIndex(seriesKey);var row=this._fetchRow(seriesIndex,rowKey);if(row===null)return null;else{var columnIndex=this.columnIndex(columnKey);return row.values[columnIndex]}};noname.KeyedValues3DDataset.prototype.addListener=function(listener){this._listeners.push(listener)};
noname.KeyedValues3DDataset.prototype.removeListener=function(listener){var i=this._listeners.indexOf(listener);if(i>=0)this._listeners.splice(i,1)};noname.KeyedValues3DDataset.prototype.notifyListeners=function(){for(var i=0;i<this._listeners.length;i++)this._listeners[i].datasetChanged(this);return this};
noname.KeyedValues3DDataset.prototype.add=function(seriesKey,rowKey,columnKey,value){if(this.isEmpty()){this.data.rowKeys.push(rowKey);this.data.columnKeys.push(columnKey);this.data.series.push({"seriesKey":seriesKey,"rows":[{"rowKey":rowKey,"values":[value]}]});this.properties.push({"seriesKey":seriesKey,"rows":[{"rowKey":rowKey,"maps":[null]}]})}else{var seriesIndex=this.seriesIndex(seriesKey);if(seriesIndex<0){this.data.series.push({"seriesKey":seriesKey,"rows":[]});this.properties.push({"seriesKey":seriesKey,
"rows":[]});seriesIndex=this.data.series.length-1}var columnIndex=this.columnIndex(columnKey);if(columnIndex<0){this.data.columnKeys.push(columnKey);for(var s=0;s<this.data.series.length;s++){var rows=this.data.series[s].rows;for(var r=0;r<rows.length;r++)rows[r].values.push(null)}for(var s=0;s<this.properties.length;s++){var rows=this.properties[s].rows;for(var r=0;r<rows.length;r++)rows[r].maps.push(null)}columnIndex=this.columnCount()-1}var rowIndex=this.rowIndex(rowKey);if(rowIndex<0){this.data.rowKeys.push(rowKey);
var rowData=noname.Utils.makeArrayOf(null,this.columnCount());rowData[columnIndex]=value;this.data.series[seriesIndex].rows.push({"rowKey":rowKey,"values":rowData});var rowMaps=noname.Utils.makeArrayOf(null,this.columnCount());this.properties[seriesIndex].rows.push({"rowKey":rowKey,"maps":rowMaps})}else{var row=this._fetchRow(seriesIndex,rowKey);if(row!==null)row.values[columnIndex]=value;else{var rowData=noname.Utils.makeArrayOf(null,this.columnCount());rowData[columnIndex]=value;this.data.series[seriesIndex].rows.push({"rowKey":rowKey,
"values":rowData})}var row=this._fetchPropertyRow(seriesIndex,rowKey);if(row===null){var rowMaps=noname.Utils.makeArrayOf(null,this.columnCount());this.properties[seriesIndex].rows.push({"rowKey":rowKey,"maps":rowMaps})}}}return this};noname.KeyedValues3DDataset.prototype.parse=function(jsonStr){this.load(JSON.parse(jsonStr));return this};
noname.KeyedValues3DDataset.prototype.load=function(dataObj){this.data=dataObj;if(!this.data.hasOwnProperty("rowKeys"))this.data.rowKeys=[];if(!this.data.hasOwnProperty("columnKeys"))this.data.columnKeys=[];if(!this.data.hasOwnProperty("series"))this.data.series=[];this.clearAllProperties();this.notifyListeners();return this};
noname.KeyedValues3DDataset.prototype.getProperty=function(seriesKey,rowKey,columnKey,propertyKey){var seriesIndex=this.seriesIndex(seriesKey);var rowIndex=this.rowIndex(rowKey);var columnIndex=this.columnIndex(columnKey);var map=this.properties[seriesIndex].rows[rowIndex][columnIndex];if(map)return map.get(propertyKey)};
noname.KeyedValues3DDataset.prototype.setProperty=function(seriesKey,rowKey,columnKey,propertyKey,value){var seriesIndex=this.seriesIndex(seriesKey);var rowIndex=this.rowIndex(rowKey);var columnIndex=this.columnIndex(columnKey);var map=this.properties[seriesIndex].rows[rowIndex][columnIndex];if(!map){map=new noname.Map;this.properties[seriesIndex].rows[rowIndex][columnIndex]=map}map.put(propertyKey,value)};
noname.KeyedValues3DDataset.prototype.propertyKeys=function(seriesKey,rowKey,columnKey){var seriesIndex=this.seriesIndex(seriesKey);var rowIndex=this.rowIndex(rowKey);var columnIndex=this.columnIndex(columnKey);var map=this.properties[seriesIndex].rows[rowIndex][columnIndex];if(map)return map.keys();else return[]};
noname.KeyedValues3DDataset.prototype.clearProperties=function(seriesKey,rowKey,columnKey){var seriesIndex=this.seriesIndex(seriesKey);var row=this._fetchPropertyRow(seriesIndex,rowKey);if(row){var columnIndex=this.columnIndex(columnKey);row[columnIndex]=null}};
noname.KeyedValues3DDataset.prototype.clearAllProperties=function(){this.properties=[];var me=this;this.data.series.forEach(function(series){var s={"seriesKey":series.seriesKey,"rows":[]};me.properties.push(s);series.rows.forEach(function(row){var maps=noname.Utils.makeArrayOf(null,me.columnCount());var r={"rowKey":row.rowKey,"maps":maps};s.rows.push(r)})})};
noname.KeyedValues3DDataset.prototype._fetchPropertyRow=function(seriesIndex,rowKey){var rows=this.properties[seriesIndex].rows;for(var r=0;r<rows.length;r++)if(rows[r].rowKey===rowKey)return rows[r];return null};noname.XYDataset=function(){this.data={"series":[]};this.properties=[];this.selections=[];this._listeners=[]};noname.XYDataset.prototype.seriesCount=function(){return this.data.series.length};noname.XYDataset.prototype.seriesKeys=function(){return this.data.series.map(function(d){return d.seriesKey})};noname.XYDataset.prototype.seriesKey=function(seriesIndex){return this.data.series[seriesIndex].seriesKey};
noname.XYDataset.prototype.seriesIndex=function(seriesKey){noname.Args.requireString(seriesKey,"seriesKey");var seriesArray=this.data.series;var seriesCount=this.data.series.length;for(var s=0;s<seriesCount;s++)if(seriesArray[s].seriesKey===seriesKey)return s;return-1};noname.XYDataset.prototype.itemCount=function(seriesIndex){return this.data.series[seriesIndex].items.length};
noname.XYDataset.prototype.itemIndex=function(seriesKey,itemKey){noname.Args.require(itemKey,"itemKey");var seriesIndex=this.seriesIndex(seriesKey);var items=this.data.series[seriesIndex].items;for(var i=0;i<items.length;i++)if(items[i].key===itemKey)return i;return-1};noname.XYDataset.prototype.x=function(seriesIndex,itemIndex){return this.data.series[seriesIndex].items[itemIndex].x};noname.XYDataset.prototype.y=function(seriesIndex,itemIndex){return this.data.series[seriesIndex].items[itemIndex].y};
noname.XYDataset.prototype.item=function(seriesIndex,itemIndex){return this.data.series[seriesIndex].items[itemIndex]};noname.XYDataset.prototype.itemByKey=function(seriesKey,itemKey){var seriesIndex=this.seriesIndex(seriesKey);var items=this.data.series[seriesIndex].items;for(var i=0;i<items.length;i++)if(items[i].key===itemKey)return items[i]};noname.XYDataset.prototype.getItemKey=function(seriesIndex,itemIndex){return this.item(seriesIndex,itemIndex).key};
noname.XYDataset.prototype.generateItemKey=function(seriesIndex){if(seriesIndex<0)return 0;var candidate=0;var max=Number.MIN_VALUE;var items=this.data.series[seriesIndex].items;for(var i=0;i<items.length;i++){if(typeof items[i].key==="number")max=Math.max(items[i].key,max);if(candidate===items[i].key)candidate=max+1}return candidate};noname.XYDataset.prototype.items=function(seriesIndex){return this.data.series[seriesIndex].items};
noname.XYDataset.prototype.allItems=function(){var result=[];for(var s=0;s<this.data.series.length;s++)result.push(this.items(s));return result};noname.XYDataset.prototype.addListener=function(listener){this._listeners.push(listener);return this};noname.XYDataset.prototype.removeListener=function(listener){var i=this._listeners.indexOf(listener);if(i>=0)this._listeners.splice(i,1);return this};
noname.XYDataset.prototype.notifyListeners=function(){for(var i=0;i<this._listeners.length;i++)this._listeners[i](this);return this};noname.XYDataset.prototype.add=function(seriesKey,x,y,notify){noname.Args.requireNumber(x,"x");var itemKey=this.generateItemKey(this.seriesIndex(seriesKey));return this.addByKey(seriesKey,itemKey,x,y,notify)};
noname.XYDataset.prototype.addByKey=function(seriesKey,itemKey,x,y,notify){noname.Args.requireString(seriesKey,"seriesKey");var notify=notify!==false;var s=this.seriesIndex(seriesKey);if(s<0){this.addSeries(seriesKey);s=this.data.series.length-1}var item=this.itemByKey(seriesKey,itemKey);if(item){item.x=x;item.y=y}else{this.data.series[s].items.push({"x":x,"y":y,"key":itemKey});this.properties[s].maps.push(null)}if(notify)this.notifyListeners();return this};
noname.XYDataset.prototype.remove=function(seriesIndex,itemIndex,notify){this.data.series[seriesIndex].items.splice(itemIndex,1);this.properties[seriesIndex].maps.splice(itemIndex,1);if(notify!==false)this.notifyListeners();return this};noname.XYDataset.prototype.removeByKey=function(seriesKey,itemKey,notify){var seriesIndex=this.seriesIndex(seriesKey);var itemIndex=this.itemIndex(itemKey);this.remove(seriesIndex,itemIndex,notify)};
noname.XYDataset.prototype.addSeries=function(seriesKey){if(!(typeof seriesKey==="string"))throw new Error("The 'seriesKey' must be a string.");var s=this.seriesIndex(seriesKey);if(s>=0)throw new Error("There is already a series with the key '"+seriesKey);this.data.series.push({"seriesKey":seriesKey,"items":[]});this.properties.push({"seriesKey":seriesKey,"maps":[]});return this};
noname.XYDataset.prototype.removeSeries=function(seriesKey){if(!(typeof seriesKey==="string"))throw new Error("The 'seriesKey' must be a string.");var s=this.seriesIndex(seriesKey);if(s>=0){this.data.series.splice(s,1);this.properties.splice(s,1)}return this};
noname.XYDataset.prototype.bounds=function(){var xmin=Number.POSITIVE_INFINITY;var xmax=Number.NEGATIVE_INFINITY;var ymin=Number.POSITIVE_INFINITY;var ymax=Number.NEGATIVE_INFINITY;for(var s=0;s<this.seriesCount();s++)for(var i=0;i<this.itemCount(s);i++){var xyitem=this.item(s,i);xmin=Math.min(xmin,xyitem.x);xmax=Math.max(xmax,xyitem.x);ymin=Math.min(ymin,xyitem.y);ymax=Math.max(ymax,xyitem.y)}return[xmin,xmax,ymin,ymax]};
noname.XYDataset.prototype.getProperty=function(seriesKey,itemKey,propertyKey){var seriesIndex=this.seriesIndex(seriesKey);var itemIndex=this.itemIndex(seriesKey,itemKey);var map=this.properties[seriesIndex].maps[itemIndex];if(map)return map.get(propertyKey)};
noname.XYDataset.prototype.setProperty=function(seriesKey,itemKey,propertyKey,value){var seriesIndex=this.seriesIndex(seriesKey);var itemIndex=this.itemIndex(seriesKey,itemKey);var map=this.properties[seriesIndex].maps[itemIndex];if(!map){map=new noname.Map;this.properties[seriesIndex].maps[itemIndex]=map}map.put(propertyKey,value)};
noname.XYDataset.prototype.clearProperties=function(seriesKey,itemKey){var seriesIndex=this.seriesIndex(seriesKey);var itemIndex=this.itemIndex(seriesKey,itemKey);this.properties[seriesIndex].maps[itemIndex]=null};
noname.XYDataset.prototype.select=function(selectionId,seriesKey,itemKey){var selection;var selectionIndex=this._indexOfSelection(selectionId);if(selectionIndex<0){selection={"id":selectionId,"items":[]};this.selections.push(selection)}else selection=this.selections[selectionIndex];var i=noname.Utils.findInArray(selection.items,function(item){return item.seriesKey===seriesKey&&item.itemKey===itemKey});if(i<0)selection.items.push({"seriesKey":seriesKey,"itemKey":itemKey});return this};
noname.XYDataset.prototype.unselect=function(selectionId,seriesKey,itemKey){var selectionIndex=this._indexOfSelection(selectionId);if(selectionIndex>=0){var selection=this.selections[selectionIndex];var i=noname.Utils.findInArray(selection.items,function(obj,i){return obj.seriesKey===seriesKey&&obj.itemKey===itemKey});if(i>=0)selection.items.splice(i,1)}return this};
noname.XYDataset.prototype.isSelected=function(selectionId,seriesKey,itemKey){var selection;var selectionIndex=this._indexOfSelection(selectionId);if(selectionIndex<0)return false;else selection=this.selections[selectionIndex];return noname.Utils.findInArray(selection.items,function(obj){return obj.seriesKey===seriesKey&&obj.itemKey===itemKey})>=0};
noname.XYDataset.prototype.clearSelection=function(selectionId){var selectionIndex=this._indexOfSelection(selectionId);if(selectionIndex>=0)this.selections.splice(selectionIndex,1);return this};noname.XYDataset.prototype._indexOfSelection=function(selectionId){return noname.Utils.findInArray(this.selections,function(item){return item.id===selectionId})};noname.XYZDataset=function(){this.data={"series":[]};this.properties=[];this.selections=[];this._listeners=[]};noname.XYZDataset.prototype.seriesCount=function(){return this.data.series.length};noname.XYZDataset.prototype.seriesKeys=function(){return this.data.series.map(function(d){return d.seriesKey})};noname.XYZDataset.prototype.seriesKey=function(seriesIndex){return this.data.series[seriesIndex].seriesKey};
noname.XYZDataset.prototype.seriesIndex=function(seriesKey){noname.Args.requireString(seriesKey,"seriesKey");var seriesArray=this.data.series;var seriesCount=this.data.series.length;for(var s=0;s<seriesCount;s++)if(seriesArray[s].seriesKey===seriesKey)return s;return-1};noname.XYZDataset.prototype.itemCount=function(seriesIndex){return this.data.series[seriesIndex].items.length};
noname.XYZDataset.prototype.itemIndex=function(seriesKey,itemKey){noname.Args.require(itemKey,"itemKey");var seriesIndex=this.seriesIndex(seriesKey);var items=this.data.series[seriesIndex].items;for(var i=0;i<items.length;i++)if(items[i].key===itemKey)return i;return-1};noname.XYZDataset.prototype.x=function(seriesIndex,itemIndex){return this.data.series[seriesIndex].items[itemIndex].x};noname.XYZDataset.prototype.y=function(seriesIndex,itemIndex){return this.data.series[seriesIndex].items[itemIndex].y};
noname.XYZDataset.prototype.z=function(seriesIndex,itemIndex){return this.data.series[seriesIndex].items[itemIndex].z};noname.XYZDataset.prototype.item=function(seriesIndex,itemIndex){return this.data.series[seriesIndex].items[itemIndex]};noname.XYZDataset.prototype.itemByKey=function(seriesKey,itemKey){var seriesIndex=this.seriesIndex(seriesKey);var items=this.data.series[seriesIndex].items;for(var i=0;i<items.length;i++)if(items[i].key===itemKey)return items[i]};
noname.XYZDataset.prototype.getItemKey=function(seriesIndex,itemIndex){return this.item(seriesIndex,itemIndex).key};noname.XYZDataset.prototype.generateItemKey=function(seriesIndex){if(seriesIndex<0)return 0;var candidate=0;var max=Number.MIN_VALUE;var items=this.data.series[seriesIndex].items;for(var i=0;i<items.length;i++){if(typeof items[i].key==="number")max=Math.max(items[i].key,max);if(candidate===items[i].key)candidate=max+1}return candidate};
noname.XYZDataset.prototype.add=function(seriesKey,x,y,z,notify){noname.Args.requireNumber(x,"x");var itemKey=this.generateItemKey(this.seriesIndex(seriesKey));return this.addByKey(seriesKey,itemKey,x,y,z,notify)};
noname.XYZDataset.prototype.addByKey=function(seriesKey,itemKey,x,y,z,notify){noname.Args.requireString(seriesKey,"seriesKey");var s=this.seriesIndex(seriesKey);if(s<0){this.addSeries(seriesKey);s=this.data.series.length-1}var item=this.itemByKey(seriesKey,itemKey);if(item){item.x=x;item.y=y}else{this.data.series[s].items.push({"x":x,"y":y,"z":z,"key":itemKey});this.properties[s].maps.push(null)}if(notify!==false)this.notifyListeners();return this};
noname.XYZDataset.prototype.addSeries=function(seriesKey){noname.Args.requireString(seriesKey,"seriesKey");var s=this.seriesIndex(seriesKey);if(s>=0)throw new Error("There is already a series with the key '"+seriesKey);this.data.series.push({"seriesKey":seriesKey,"items":[]});this.properties.push({"seriesKey":seriesKey,"maps":[]});return this};
noname.XYZDataset.prototype.removeSeries=function(seriesKey){noname.Args.requireString(seriesKey,"seriesKey");var s=this.seriesIndex(seriesKey);if(s>=0)this.data.series.splice(s,1);return this};noname.XYZDataset.prototype.addListener=function(listener){this._listeners.push(listener);return this};noname.XYZDataset.prototype.removeListener=function(listener){var i=this._listeners.indexOf(listener);if(i>=0)this._listeners.splice(i,1);return this};
noname.XYZDataset.prototype.notifyListeners=function(){for(var i=0;i<this._listeners.length;i++)this._listeners[i](this);return this};noname.XYZDataset.prototype.getProperty=function(seriesKey,itemKey,propertyKey){var seriesIndex=this.seriesIndex(seriesKey);var itemIndex=this.itemIndex(seriesKey,itemKey);var map=this.properties[seriesIndex].maps[itemIndex];if(map)return map.get(propertyKey)};
noname.XYZDataset.prototype.setProperty=function(seriesKey,itemKey,propertyKey,value){var seriesIndex=this.seriesIndex(seriesKey);var itemIndex=this.itemIndex(seriesKey,itemKey);var map=this.properties[seriesIndex][itemIndex];if(!map){map=new noname.Map;this.properties[seriesIndex].maps[itemIndex]=map}map.put(propertyKey,value)};
noname.XYZDataset.prototype.clearProperties=function(seriesKey,itemKey){var seriesIndex=this.seriesIndex(seriesKey);var itemIndex=this.itemIndex(seriesKey,itemKey);this.properties[seriesIndex].maps[itemIndex]=null};
noname.XYZDataset.prototype.select=function(selectionId,seriesKey,itemIndex){var selection;var selectionIndex=this._indexOfSelection(selectionId);if(selectionIndex<0){selection={"id":selectionId,"items":[]};this.selections.push(selection)}else selection=this.selections[selectionIndex];var i=noname.Utils.findInArray(selection.items,function(item){return item.seriesKey===seriesKey&&item.item===itemIndex});if(i<0)selection.items.push({"seriesKey":seriesKey,"item":itemIndex});return this};
noname.XYZDataset.prototype.unselect=function(selectionId,seriesKey,itemIndex){var selectionIndex=this._indexOfSelection(selectionId);if(selectionIndex>=0){var selection=this.selections[selectionIndex];var i=noname.Utils.findInArray(selection.items,function(obj,i){return obj.seriesKey===seriesKey&&obj.item===itemIndex});if(i>=0)selection.items.splice(i,1)}return this};
noname.XYZDataset.prototype.isSelected=function(selectionId,seriesKey,itemIndex){var selection;var selectionIndex=this._indexOfSelection(selectionId);if(selectionIndex<0)return false;else selection=this.selections[selectionIndex];return noname.Utils.findInArray(selection.items,function(obj){return obj.seriesKey===seriesKey&&obj.item===itemIndex})>=0};
noname.XYZDataset.prototype.clearSelection=function(selectionId){var selectionIndex=this._indexOfSelection(selectionId);if(selectionIndex>=0)this.selections.splice(selectionIndex,1)};noname.XYZDataset.prototype._indexOfSelection=function(selectionId){return noname.Utils.findInArray(this.selections,function(item){return item.id===selectionId})};noname.KeyedValueLabels=function(){if(!(this instanceof noname.KeyedValueLabels))return new noname.KeyedValueLabels;this.format="{K} = {V}";this.valueDP=2;this.percentDP=2};
noname.KeyedValueLabels.prototype.itemLabel=function(keyedValues,itemIndex){var labelStr=new String(this.format);var keyStr=keyedValues.key(itemIndex);var value=keyedValues.valueByIndex(itemIndex);var valueStr=value.toFixed(this.valueDP);var total=keyedValues.total();var percentStr=(value/total*100).toFixed(this.percentDP);labelStr=labelStr.replace(/{K}/g,keyStr);labelStr=labelStr.replace(/{V}/g,valueStr);labelStr=labelStr.replace(/{P}/g,percentStr);return labelStr};noname.KeyedValue2DLabels=function(){if(!(this instanceof noname.KeyedValue2DLabels))return new noname.KeyedValue2DLabels;this.format="{R}, {C} = {V}";this.valueDP=2};
noname.KeyedValue2DLabels.prototype.itemLabel=function(keyedValues2D,rowIndex,columnIndex){var labelStr=new String(this.format);var rowKeyStr=keyedValues2D.rowKey(rowIndex);var columnKeyStr=keyedValues2D.columnKey(columnIndex);var value=keyedValues2D.valueByIndex(rowIndex,columnIndex);var valueStr=value.toFixed(this.valueDP);labelStr=labelStr.replace(/{R}/g,rowKeyStr);labelStr=labelStr.replace(/{C}/g,columnKeyStr);labelStr=labelStr.replace(/{V}/g,valueStr);return labelStr};noname.KeyedValue3DLabels=function(){if(!(this instanceof noname.KeyedValue3DLabels))return new noname.KeyedValue3DLabels;this.format="{S}, {R}, {C} = {V}";this.valueDP=2};
noname.KeyedValue3DLabels.prototype.itemLabel=function(keyedValues3D,seriesIndex,rowIndex,columnIndex){var labelStr=new String(this.format);var seriesKeyStr=keyedValues3D.seriesKey(seriesIndex);var rowKeyStr=keyedValues3D.rowKey(rowIndex);var columnKeyStr=keyedValues3D.columnKey(columnIndex);var value=keyedValues3D.valueByIndex(seriesIndex,rowIndex,columnIndex);var valueStr=value.toFixed(this.valueDP);labelStr=labelStr.replace(/{S}/g,seriesKeyStr);labelStr=labelStr.replace(/{R}/g,rowKeyStr);labelStr=
labelStr.replace(/{C}/g,columnKeyStr);labelStr=labelStr.replace(/{V}/g,valueStr);return labelStr};noname.XYLabels=function(){if(!(this instanceof noname.XYLabels))return new noname.XYLabels;this.format="{X}, {Y} / {S}";this.xDP=2;this.yDP=2};
noname.XYLabels.prototype.itemLabel=function(dataset,seriesKey,itemIndex){var labelStr=new String(this.format);var seriesKeyStr=seriesKey;var seriesIndex=dataset.seriesIndex(seriesKey);var item=dataset.item(seriesIndex,itemIndex);var xStr=item.x.toFixed(this.xDP);var yStr=item.y.toFixed(this.yDP);labelStr=labelStr.replace(/{X}/g,xStr);labelStr=labelStr.replace(/{Y}/g,yStr);labelStr=labelStr.replace(/{S}/g,seriesKeyStr);return labelStr};noname.XYZLabels=function(){if(!(this instanceof noname.XYZLabels))return new noname.XYZLabels;this.format="{X}, {Y}, {Z} / {S}";this.xDP=2;this.yDP=2;this.zDP=2};
noname.XYZLabels.prototype.itemLabel=function(dataset,seriesKey,itemIndex){var labelStr=new String(this.format);var seriesKeyStr=seriesKey;var seriesIndex=dataset.seriesIndex(seriesKey);var item=dataset.item(seriesIndex,itemIndex);var xStr=item.x.toFixed(this.xDP);var yStr=item.y.toFixed(this.yDP);var zStr=item.z.toFixed(this.zDP);labelStr=labelStr.replace(/{X}/g,xStr);labelStr=labelStr.replace(/{Y}/g,yStr);labelStr=labelStr.replace(/{Z}/g,zStr);labelStr=labelStr.replace(/{S}/g,seriesKeyStr);return labelStr};
